// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TechDebt struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TechDebt             int64    `protobuf:"varint,2,opt,name=techDebt,proto3" json:"techDebt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TechDebt) Reset()         { *m = TechDebt{} }
func (m *TechDebt) String() string { return proto.CompactTextString(m) }
func (*TechDebt) ProtoMessage()    {}
func (*TechDebt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *TechDebt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TechDebt.Unmarshal(m, b)
}
func (m *TechDebt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TechDebt.Marshal(b, m, deterministic)
}
func (m *TechDebt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TechDebt.Merge(m, src)
}
func (m *TechDebt) XXX_Size() int {
	return xxx_messageInfo_TechDebt.Size(m)
}
func (m *TechDebt) XXX_DiscardUnknown() {
	xxx_messageInfo_TechDebt.DiscardUnknown(m)
}

var xxx_messageInfo_TechDebt proto.InternalMessageInfo

func (m *TechDebt) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TechDebt) GetTechDebt() int64 {
	if m != nil {
		return m.TechDebt
	}
	return 0
}

func init() {
	proto.RegisterType((*TechDebt)(nil), "TechDebt")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe2, 0xe2, 0x08, 0x49,
	0x4d, 0xce, 0x70, 0x49, 0x4d, 0x2a, 0x11, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x25, 0x50, 0x75,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x70, 0x7e, 0x12, 0x1b, 0xd8, 0x28, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x10, 0x4e, 0x34, 0x5c, 0x00, 0x00, 0x00,
}
